language: python
python:
- "3.6"
- "3.7"
- "3.8"
install:
- pip install pytest==5.4.3
- pip install pytest-cov==2.10.0
- pip install codecov==2.1.8
- python setup.py develop
script:
- pytest --cov
after_success:
- codecov
